<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.qa</groupId>
        <artifactId>qa-teste-tecnico</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>performance-tests</artifactId>
    <packaging>jar</packaging>

    <properties>
        <junit.version>5.10.2</junit.version>
        <jmeter-java-dsl.version>1.29.1</jmeter-java-dsl.version>
    </properties>

    <dependencies>
        <!-- JUnit 5 -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- JMeter Java DSL -->
        <dependency>
            <groupId>us.abstracta.jmeter</groupId>
            <artifactId>jmeter-java-dsl</artifactId>
            <version>${jmeter-java-dsl.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <argLine>-Xmx2048m</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
